---
title: "dashboard_about"
author: "Emily Wapman"
date: "2026-08-18"
output: html_document
---

### **Dashboard overview**

Sequencing for this project was focused on detecting fishes and mammals. The full list of <span style="color: blue !important;">**129 detections**</span> was narrowed for these visualizations to focus on <span style="color: teal !important;">**50 indicator species**</span> important to Monterey Bay National Marine Sanctuary. 

### **What is an indicator species?**

Indicator species are organisms whose population levels can indicate broader changes in environmental conditions, acting as an early warning system for ecosystem health. For example, declining population levels of an indicator species could signal changes in water quality, temperature, or food source availability.

### **Definitions:**

**Detection:** The organism's DNA was present in a sample. This is a presence measure. Each sample is counted once per organism regardless of abundance.

**Deep Chlorophyll Max (DCM):** The subsurface layer with the highest amount of chlorophyll. Varies depending on nutrient and light availability. 
