---
title: "dna_background"
author: "Emily Wapman"
date: "2026-07-28"
output: html_document
---

### What is DNA?

DNA is a molecule found in an organism’s cell that provides instructions for development. DNA molecules consist of a sequence of building blocks, or nucleotides, made up of adenine (A), cytosine (C), guanine (G), and thymine (T). Each organism’s nucleotides are arranged in a unique sequence.

### What is eDNA?

Environmental DNA (eDNA) refers to the DNA that is found naturally in the environment as organisms shed cells, hair, feces, and mucus. Scientists can extract DNA from soil, water, or air samples, analyze the unique nucleotide sequences, and assign these sequences to organism names.

### What can eDNA tell us?

eDNA can tell us what organisms are present or were recently present in an area.

### What can eDNA *not* tell us?

For eDNA sequenced for a specific gene, it can be difficult to show: 
- Population size
- If the organisms are alive or dead
- The life stage of an organism
- The exact location of an organism
- The sex of an organism
- The absence of an organism (eDNA can have false negatives, meaning an organism could be present in the environment even if its DNA is not detected in a sample.)
