---
title: "depth_about"
author: "Emily Wapman"
date: "2026-07-31"
output: html_document
---

### **How do indicator taxa detections change over depth?**

eDNA surveys can be a useful method for detecting organisms deeper in the water column without deploying Remotely Operated Vehicles (ROVs).

The graph shows the relative abundance of each organism detected during the selected season(s) at each depth. **For example, at 300m, each organism made up X% of all samples at that depth.** Larger circles indicate a higher relative abundance. Selecting a unique taxa at the top of the page highlights the data points in <span style="color: darkorange;">orange</span>.

The <span style="color: green;">deep chlorophyll max</span> varies spatially and temporally with changes in nutrient and light availability. All detections at the deep chlorophyll max were grouped into one sampling depth category for calculations. <span style="color: green;"> The highlighted section shows the range of deep chlorophyll max values sampled for the selected season(s).</span>

*Select a taxa and season(s) at the top of the page. Hover over points to view details.*
