---
title: "synchro_about"
author: "Emily Wapman"
date: "2026-07-28"
output: html_document
---

### Synchro project:

The goal of the Synchro project is to assess how eDNA can be used to monitor marine biodiversity and the impacts of offshore wind farms.

Samples were collected at 6 stations along a transect ranging from Elkhorn Slough (ES) to an offshore wind station (OSWS) for three dates each in April, July, and October 2025. For these visualizations, all April dates are grouped as Spring 2025, the July dates as Summer 2025, and the October dates as Autumn 2025.

At Elkhorn Slough, water samples were collected using 4 buckets at the surface for three replicates. At each of the other stations, water samples were collected using a CTD cast, an instrument lowered into the water to collect samples and environmental data (temperature, salinity, oxygen, etc.) at defined depths: 0 meters, the deep chlorophyll maximum, 150 meters, and 300 meters, for three replicates. The deep chlorophyll max depth varies depending on nutrient and light availability.

Beyond water samples, air samples were also collected. For surface samples, passive sampling using a TorpeDNA device (DNA is filtered as the device is towed through the water) was compared to active sampling (water is pumped mechanically through a filter on-board to filter out DNA).
